FROM maven:3.6-jdk-8

WORKDIR /app

# Copy the parent pom first
COPY pom.xml ./pom.xml
COPY api-gateway/pom.xml ./api-gateway/pom.xml
COPY api-gateway/src ./api-gateway/src

WORKDIR /app/api-gateway

CMD ["mvn", "spring-boot:run"]