FROM maven:3.6-jdk-8

WORKDIR /app

# Copy the parent pom first
COPY pom.xml ./pom.xml
COPY eureka-server/pom.xml ./eureka-server/pom.xml
COPY eureka-server/src ./eureka-server/src

WORKDIR /app/eureka-server

CMD ["mvn", "spring-boot:run"]