services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-user_service_dev}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile.prod
    restart: always
    ports:
      - "${EUREKA_PORT}:8761"
    networks:
      - backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms256m -Xmx512m
      - EUREKA_HOSTNAME=eureka-server
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 60s
    volumes:
      - ./eureka-server:/build/eureka-server
      - ./user-service:/build/user-service
      - ./email-service:/build/email-service
      - ./api-gateway:/build/api-gateway
      - ./pom.xml:/build/pom.xml

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile.prod
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-user_service_dev}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD}
      - SEED_REGULAR_USER_EMAIL=${SEED_REGULAR_USER_EMAIL}
      - SEED_REGULAR_USER_PASSWORD=${SEED_REGULAR_USER_PASSWORD}
      - SPRING_CLOUD_CONFIG_FAIL_FAST=true
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - backend
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 768M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - ./eureka-server:/build/eureka-server
      - ./user-service:/build/user-service
      - ./email-service:/build/email-service
      - ./api-gateway:/build/api-gateway
      - ./pom.xml:/build/pom.xml

  email-service:
    build:
      context: .
      dockerfile: email-service/Dockerfile.prod
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - backend
    depends_on:
      eureka-server:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./email-service:/build/email-service
      - ./user-service:/build/user-service
      - ./eureka-server:/build/eureka-server
      - ./api-gateway:/build/api-gateway
      - ./pom.xml:/build/pom.xml

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile.prod
    restart: always
    ports:
      - "${API_GATEWAY_PORT}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ZUUL_HOST_CONNECT-TIMEOUT-MILLIS=20000
      - ZUUL_HOST_SOCKET-TIMEOUT-MILLIS=20000
      - RIBBON_CONNECT-TIMEOUT=10000
      - RIBBON_READ-TIMEOUT=20000
      - HYSTRIX_COMMAND_DEFAULT_EXECUTION_ISOLATION_THREAD_TIMEOUT-IN-MILLISECONDS=20000
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - backend
      - frontend
    depends_on:
      user-service:
        condition: service_healthy
      email-service:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 768M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./eureka-server:/build/eureka-server
      - ./user-service:/build/user-service
      - ./email-service:/build/email-service
      - ./api-gateway:/build/api-gateway
      - ./pom.xml:/build/pom.xml


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: false

volumes:
  mysql_data:
    driver: local