server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

zuul:
  routes:
    auth:
      path: /api/auth/**
      serviceId: user-service
      stripPrefix: false
    users:
      path: /api/users/**
      serviceId: user-service
      stripPrefix: false
    email:
      path: /api/email/**
      serviceId: email-service
      stripPrefix: false
  sensitive-headers: Cookie,Set-Cookie
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  ribbon:
    eager-load:
      enabled: true

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
  eureka:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true

jwt:
  secret: ${JWT_SECRET:your_secret_key}
  expiration: ${JWT_EXPIRATION:86400000}
