spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: yourSecretKey
  expiration: 86400000 # 24 hours

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_dev?createDatabaseIfNotExist=true
    username: root
    password: root
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_qa?createDatabaseIfNotExist=true
    username: root
    password: root
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://prod-db:3306/user_service_prod
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/