spring:
  config:
    activate:
      on-profile: qa
  datasource:
    url: jdbc:mysql://localhost:3306/user_service_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/