FROM maven:3.6-jdk-8

WORKDIR /app

# Copy the parent pom first
COPY pom.xml ./pom.xml
COPY email-service/pom.xml ./email-service/pom.xml
COPY email-service/src ./email-service/src

WORKDIR /app/email-service

CMD ["mvn", "spring-boot:run"]