spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
    enableSelfPreservation: true
