spring:
  config:
    activate:
      on-profile: qa
  mail:
    host: smtp.gmail.com
    port: 587
    username: qa-test@genericcompany.com
    password: your-qa-password
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
