spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-generated-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true